// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ajBd7QwKoQEZw4eSnuM8eE
// Component: V29gw2H4lR
import * as React from "react"

import { Link, GatsbyLinkProps as LinkProps } from "gatsby"

import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"

import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_jorgekauffman_com.module.css" // plasmic-import: ajBd7QwKoQEZw4eSnuM8eE/projectcss
import * as sty from "./PlasmicOffering.module.css" // plasmic-import: V29gw2H4lR/css

export type PlasmicOffering__VariantMembers = {}

export type PlasmicOffering__VariantsArgs = {}
type VariantPropType = keyof PlasmicOffering__VariantsArgs
export const PlasmicOffering__VariantProps = new Array<VariantPropType>()

export type PlasmicOffering__ArgsType = {}
type ArgPropType = keyof PlasmicOffering__ArgsType
export const PlasmicOffering__ArgProps = new Array<ArgPropType>()

export type PlasmicOffering__OverridesType = {
  root?: p.Flex<"div">
}

export interface DefaultOfferingProps {
  className?: string
}

function PlasmicOffering__RenderFunc(props: {
  variants: PlasmicOffering__VariantsArgs
  args: PlasmicOffering__ArgsType
  overrides: PlasmicOffering__OverridesType
  dataFetches?: PlasmicOffering__Fetches
  forNode?: string
}) {
  const { variants, args, overrides, forNode, dataFetches } = props

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__oRtqd)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__wcJQn
          )}
        >
          {"Offering"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box___0AjYe
          )}
        >
          {
            "Experience Design\neLearning Design & Development \nApplied Instructional Design \nVisual Design\nLearning Design \nWeb Design\nContent Pipeline Ownership\nPeople, SME and Stakeholder Relationship Management"
          }
        </div>
      </div>
    </div>
  ) as React.ReactElement | null
}

const PlasmicDescendants = {
  root: ["root"],
} as const
type NodeNameType = keyof typeof PlasmicDescendants
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number]
type NodeDefaultElementType = {
  root: "div"
}

type ReservedPropsType = "variants" | "args" | "overrides"
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOffering__OverridesType,
  DescendantsType<T>
>
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicOffering__VariantsArgs
  args?: PlasmicOffering__ArgsType
  overrides?: NodeOverridesType<T>
  dataFetches?: PlasmicOffering__Fetches
} & Omit<PlasmicOffering__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicOffering__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key }
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicOffering__ArgProps,
      internalVariantPropNames: PlasmicOffering__VariantProps,
    })

    const { dataFetches } = props

    return PlasmicOffering__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicOffering"
  } else {
    func.displayName = `PlasmicOffering.${nodeName}`
  }
  return func
}

export const PlasmicOffering = Object.assign(
  // Top-level PlasmicOffering renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicOffering
    internalVariantProps: PlasmicOffering__VariantProps,
    internalArgProps: PlasmicOffering__ArgProps,
  }
)

export default PlasmicOffering
/* prettier-ignore-end */
