// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ajBd7QwKoQEZw4eSnuM8eE
// Component: V29gw2H4lR
import * as React from "react"

import { Link, GatsbyLinkProps as LinkProps } from "gatsby"

import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"

import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_jorgekauffman_com.module.css" // plasmic-import: ajBd7QwKoQEZw4eSnuM8eE/projectcss
import * as sty from "./PlasmicSkill.module.css" // plasmic-import: V29gw2H4lR/css

export type PlasmicSkill__VariantMembers = {}

export type PlasmicSkill__VariantsArgs = {}
type VariantPropType = keyof PlasmicSkill__VariantsArgs
export const PlasmicSkill__VariantProps = new Array<VariantPropType>()

export type PlasmicSkill__ArgsType = {}
type ArgPropType = keyof PlasmicSkill__ArgsType
export const PlasmicSkill__ArgProps = new Array<ArgPropType>()

export type PlasmicSkill__OverridesType = {
  root?: p.Flex<"div">
  box?: p.Flex<"div">
}

export interface DefaultSkillProps {
  className?: string
}

function PlasmicSkill__RenderFunc(props: {
  variants: PlasmicSkill__VariantsArgs
  args: PlasmicSkill__ArgsType
  overrides: PlasmicSkill__OverridesType
  dataFetches?: PlasmicSkill__Fetches
  forNode?: string
}) {
  const { variants, args, overrides, forNode, dataFetches } = props

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, defaultcss.__wab_text, sty.box)}
      >
        {"Technical Skill"}
      </div>
    </div>
  ) as React.ReactElement | null
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"],
} as const
type NodeNameType = keyof typeof PlasmicDescendants
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number]
type NodeDefaultElementType = {
  root: "div"
  box: "div"
}

type ReservedPropsType = "variants" | "args" | "overrides"
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSkill__OverridesType,
  DescendantsType<T>
>
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicSkill__VariantsArgs
  args?: PlasmicSkill__ArgsType
  overrides?: NodeOverridesType<T>
  dataFetches?: PlasmicSkill__Fetches
} & Omit<PlasmicSkill__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicSkill__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key }
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSkill__ArgProps,
      internalVariantPropNames: PlasmicSkill__VariantProps,
    })

    const { dataFetches } = props

    return PlasmicSkill__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicSkill"
  } else {
    func.displayName = `PlasmicSkill.${nodeName}`
  }
  return func
}

export const PlasmicSkill = Object.assign(
  // Top-level PlasmicSkill renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),

    // Metadata about props expected for PlasmicSkill
    internalVariantProps: PlasmicSkill__VariantProps,
    internalArgProps: PlasmicSkill__ArgProps,
  }
)

export default PlasmicSkill
/* prettier-ignore-end */
