// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ajBd7QwKoQEZw4eSnuM8eE
// Component: EkB8C0-Ntx
import * as React from "react"

import { Link, GatsbyLinkProps as LinkProps } from "gatsby"

import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"

import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_jorgekauffman_com.module.css" // plasmic-import: ajBd7QwKoQEZw4eSnuM8eE/projectcss
import * as sty from "./PlasmicClients.module.css" // plasmic-import: EkB8C0-Ntx/css

import AppletisersvgIcon from "./icons/PlasmicIcon__Appletisersvg" // plasmic-import: WzK2HmrWNy/icon
import Bidvestsvg2Icon from "./icons/PlasmicIcon__Bidvestsvg2" // plasmic-import: DI7i8q4a_B/icon

export type PlasmicClients__VariantMembers = {}

export type PlasmicClients__VariantsArgs = {}
type VariantPropType = keyof PlasmicClients__VariantsArgs
export const PlasmicClients__VariantProps = new Array<VariantPropType>()

export type PlasmicClients__ArgsType = {
  children?: React.ReactNode
  children2?: React.ReactNode
}

type ArgPropType = keyof PlasmicClients__ArgsType
export const PlasmicClients__ArgProps = new Array<ArgPropType>(
  "children",
  "children2"
)

export type PlasmicClients__OverridesType = {
  root?: p.Flex<"div">
}

export interface DefaultClientsProps {
  children?: React.ReactNode
  children2?: React.ReactNode
  className?: string
}

function PlasmicClients__RenderFunc(props: {
  variants: PlasmicClients__VariantsArgs
  args: PlasmicClients__ArgsType
  overrides: PlasmicClients__OverridesType
  dataFetches?: PlasmicClients__Fetches
  forNode?: string
}) {
  const { variants, args, overrides, forNode, dataFetches } = props

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        className={classNames(
          defaultcss.all,
          defaultcss.__wab_text,
          sty.box__vYkOy
        )}
      >
        {"Clients"}
      </div>

      <div className={classNames(defaultcss.all, sty.box__n9Cq)}>
        {p.renderPlasmicSlot({
          defaultContents: (
            <AppletisersvgIcon
              className={classNames(defaultcss.all, sty.svg__maExI)}
              role={"img"}
            />
          ),

          value: args.children,
          className: classNames(sty.slotChildren),
        })}

        {p.renderPlasmicSlot({
          defaultContents: (
            <Bidvestsvg2Icon
              className={classNames(defaultcss.all, sty.svg__tnx2)}
              role={"img"}
            />
          ),

          value: args.children2,
          className: classNames(sty.slotChildren2),
        })}
      </div>
    </div>
  ) as React.ReactElement | null
}

const PlasmicDescendants = {
  root: ["root"],
} as const
type NodeNameType = keyof typeof PlasmicDescendants
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number]
type NodeDefaultElementType = {
  root: "div"
}

type ReservedPropsType = "variants" | "args" | "overrides"
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicClients__OverridesType,
  DescendantsType<T>
>
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicClients__VariantsArgs
  args?: PlasmicClients__ArgsType
  overrides?: NodeOverridesType<T>
  dataFetches?: PlasmicClients__Fetches
} & Omit<PlasmicClients__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicClients__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key }
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicClients__ArgProps,
      internalVariantPropNames: PlasmicClients__VariantProps,
    })

    const { dataFetches } = props

    return PlasmicClients__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicClients"
  } else {
    func.displayName = `PlasmicClients.${nodeName}`
  }
  return func
}

export const PlasmicClients = Object.assign(
  // Top-level PlasmicClients renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicClients
    internalVariantProps: PlasmicClients__VariantProps,
    internalArgProps: PlasmicClients__ArgProps,
  }
)

export default PlasmicClients
/* prettier-ignore-end */
