// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ajBd7QwKoQEZw4eSnuM8eE
// Component: GbxbaH1_Ix
import * as React from "react"

import { Link, GatsbyLinkProps as LinkProps } from "gatsby"

import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"

import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_jorgekauffman_com.module.css" // plasmic-import: ajBd7QwKoQEZw4eSnuM8eE/projectcss
import * as sty from "./PlasmicTestimonials.module.css" // plasmic-import: GbxbaH1_Ix/css

export type PlasmicTestimonials__VariantMembers = {}

export type PlasmicTestimonials__VariantsArgs = {}
type VariantPropType = keyof PlasmicTestimonials__VariantsArgs
export const PlasmicTestimonials__VariantProps = new Array<VariantPropType>()

export type PlasmicTestimonials__ArgsType = {}
type ArgPropType = keyof PlasmicTestimonials__ArgsType
export const PlasmicTestimonials__ArgProps = new Array<ArgPropType>()

export type PlasmicTestimonials__OverridesType = {
  root?: p.Flex<"div">
}

export interface DefaultTestimonialsProps {
  className?: string
}

function PlasmicTestimonials__RenderFunc(props: {
  variants: PlasmicTestimonials__VariantsArgs
  args: PlasmicTestimonials__ArgsType
  overrides: PlasmicTestimonials__OverridesType
  dataFetches?: PlasmicTestimonials__Fetches
  forNode?: string
}) {
  const { variants, args, overrides, forNode, dataFetches } = props

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__k6XyN)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__j9DbV
          )}
        >
          {"What my colleagues say"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__efcLh
          )}
        >
          {"Expert second opinions"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null
}

const PlasmicDescendants = {
  root: ["root"],
} as const
type NodeNameType = keyof typeof PlasmicDescendants
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number]
type NodeDefaultElementType = {
  root: "div"
}

type ReservedPropsType = "variants" | "args" | "overrides"
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestimonials__OverridesType,
  DescendantsType<T>
>
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicTestimonials__VariantsArgs
  args?: PlasmicTestimonials__ArgsType
  overrides?: NodeOverridesType<T>
  dataFetches?: PlasmicTestimonials__Fetches
} & Omit<PlasmicTestimonials__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicTestimonials__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key }
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTestimonials__ArgProps,
      internalVariantPropNames: PlasmicTestimonials__VariantProps,
    })

    const { dataFetches } = props

    return PlasmicTestimonials__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicTestimonials"
  } else {
    func.displayName = `PlasmicTestimonials.${nodeName}`
  }
  return func
}

export const PlasmicTestimonials = Object.assign(
  // Top-level PlasmicTestimonials renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTestimonials
    internalVariantProps: PlasmicTestimonials__VariantProps,
    internalArgProps: PlasmicTestimonials__ArgProps,
  }
)

export default PlasmicTestimonials
/* prettier-ignore-end */
